### PR TITLE
update to latest versions (Quarkus 3)

### PR DESCRIPTION
**Pull request by kdubois**

### CODE REVIEW

**Comment by kdubois** [comment]
https://github.com/redhat-developer-demos/quarkus-tutorial/issues/111

**Comment by edeandrea** [comment]
I'm not sure you need panache/hibernate reactive. I only updated to use RESTEasy Reactive

**Comment by kdubois** [comment]
oh ok.   do we want to update the tutorial to use hibernate reactive or change it back here?

**Comment by edeandrea** [comment]
Honestly I think leaving it as blocking would make more sense for now as a "getting started". You'd have to re-write some of the tutorial as well if you want to switch it to hibernate reactive. Plus you'd force the app to be reactive (reactive rest endpoints/etc)

**Comment by kdubois** [comment]
ok sounds good, I'll change it back

**Comment by kdubois** [comment]
https://github.com/redhat-developer-demos/quarkus-maven-repo-cachier/pull/4

**Pull request merged**
